<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro">

  <xacro:macro name="simple_arm" params="prefix:='arm_'">

    <!-- 机械臂参数定义 - 与底盘风格一致 -->
    <xacro:property name="base_radius" value="0.04" />  
    <xacro:property name="base_height" value="0.05" />  
    <xacro:property name="base_mass" value="0.5" />      
    <xacro:property name="link1_length" value="0.15" />  
    <xacro:property name="link2_length" value="0.12" />  
    <xacro:property name="link3_length" value="0.08" />  
    <xacro:property name="link_radius" value="0.015" />  
    <xacro:property name="link1_mass" value="0.3" />     
    <xacro:property name="link2_mass" value="0.2" />     
    <xacro:property name="link3_mass" value="0.1" />     
    <xacro:property name="gripper_length" value="0.05" /> 
    <xacro:property name="gripper_width" value="0.03" />  
    <xacro:property name="gripper_mass" value="0.05" />   

    <!-- 机械臂材质定义 -->
    <material name="arm_silver">
      <color rgba="0.8 0.8 0.8 1.0"/>
    </material>
    
    <material name="arm_dark_gray">
      <color rgba="0.3 0.3 0.3 1.0"/>
    </material>

    <!-- 机械臂基座连接到底盘 - 安装在底盘顶部中央 -->
    <joint name="${prefix}base_joint" type="fixed">
      <parent link="base_link" />
      <child link="${prefix}base_link" />
      <origin xyz="0.0 0.0 ${0.12}" rpy="0 0 0" />
    </joint>

    <!-- 1. 机械臂基座 -->
    <link name="${prefix}base_link">
      <visual>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${base_radius}" length="${base_height}" />
        </geometry>
        <material name="arm_dark_gray" />
      </visual>
      <collision>
        <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${base_radius}" length="${base_height}" />
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${base_mass}" r="${base_radius}" h="${base_height}" />
    </link>

    <!-- 2. 第一个旋转关节 (肩部旋转) -->
    <joint name="${prefix}shoulder_pan_joint" type="revolute">
      <parent link="${prefix}base_link" />
      <child link="${prefix}link1" />
      <origin xyz="0 0 ${base_height/2}" rpy="0 0 0" />
      <axis xyz="0 0 1" />
      <limit lower="${-pi}" upper="${pi}" effort="10" velocity="1.0" />
    </joint>

    <link name="${prefix}link1">
      <visual>
        <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${link_radius}" length="${link1_length}" />
        </geometry>
        <material name="arm_silver" />
      </visual>
      <collision>
        <origin xyz="0 0 ${link1_length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${link_radius}" length="${link1_length}" />
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${link1_mass}" r="${link_radius}" h="${link1_length}" />
    </link>

    <!-- 3. 第二个俯仰关节 (肩部俯仰) -->
    <joint name="${prefix}shoulder_pitch_joint" type="revolute">
      <parent link="${prefix}link1" />
      <child link="${prefix}link2" />
      <origin xyz="0 0 ${link1_length}" rpy="${pi/2} 0 0" />
      <axis xyz="0 1 0" />
      <limit lower="${-pi/2}" upper="${pi/2}" effort="8" velocity="1.0" />
    </joint>

    <link name="${prefix}link2">
      <visual>
        <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${link_radius}" length="${link2_length}" />
        </geometry>
        <material name="arm_silver" />
      </visual>
      <collision>
        <origin xyz="0 0 ${link2_length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${link_radius}" length="${link2_length}" />
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${link2_mass}" r="${link_radius}" h="${link2_length}" />
    </link>

    <!-- 4. 第三个俯仰关节 (肘部俯仰) -->
    <joint name="${prefix}elbow_pitch_joint" type="revolute">
      <parent link="${prefix}link2" />
      <child link="${prefix}link3" />
      <origin xyz="0 0 ${link2_length}" rpy="0 0 0" />
      <axis xyz="0 1 0" />
      <limit lower="${-pi/2}" upper="${pi/2}" effort="5" velocity="1.0" />
    </joint>

    <link name="${prefix}link3">
      <visual>
        <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${link_radius}" length="${link3_length}" />
        </geometry>
        <material name="arm_silver" />
      </visual>
      <collision>
        <origin xyz="0 0 ${link3_length/2}" rpy="0 0 0" />
        <geometry>
          <cylinder radius="${link_radius}" length="${link3_length}" />
        </geometry>
      </collision>
      <xacro:cylinder_inertia m="${link3_mass}" r="${link_radius}" h="${link3_length}" />
    </link>

    <!-- 5. 末端执行器 (简单的夹爪) -->
    <joint name="${prefix}gripper_fixed_joint" type="fixed">
      <parent link="${prefix}link3" />
      <child link="${prefix}gripper_link" />
      <origin xyz="0 0 ${link3_length}" rpy="0 0 0" />
    </joint>

    <link name="${prefix}gripper_link">
      <visual>
        <origin xyz="0 0 ${gripper_length/2}" rpy="${pi/2} 0 0" />
        <geometry>
          <box size="${gripper_width} 0.01 ${gripper_length}" />
        </geometry>
        <material name="arm_dark_gray" />
      </visual>
      <collision>
        <origin xyz="0 0 ${gripper_length/2}" rpy="${pi/2} 0 0" />
        <geometry>
          <box size="${gripper_width} 0.01 ${gripper_length}" />
        </geometry>
      </collision>
      <!-- 使用圆柱体惯性近似长方体夹爪 -->
      <xacro:cylinder_inertia m="${gripper_mass}" r="${gripper_width/2}" h="0.01" />
    </link>

  </xacro:macro>

</robot>
